### ISSUE TITLE
active crash

### ISSUE THREAD

**Issue by sanitpeng** [umdevelopera/um-polylang#1]
Hello, I hope you don't mind. This extension you've created is exactly what we need. Thank you.
However, after I installed it and tried to activate it, it prompted a crash.
My system:
wordpress:6.1.1
polylang:3.4.4
ultimate-member:2.6.8

crash log:

Fatal error: Uncaught Error: Call to a member function get_prop() on bool in /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/um-polylang/includes/core/class-um-polylang.php:127 
Stack trace: 
```
#0 /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/um-polylang/includes/core/class-mail.php(159): UM_Polylang->get_current() 
#1 /usr/local/lighthouse/softwares/wordpress/wp-includes/class-wp-hook.php(308): um_ext\um_polylang\core\Mail->email_table_items() 
#2 /usr/local/lighthouse/softwares/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters() 
#3 /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/ultimate-member/includes/class-config.php(330): apply_filters() 
#4 /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/ultimate-member/includes/class-init.php(1051): um\Config->__construct() 
#5 /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/ultimate-member/includes/admin/core/class-admin-settings.php(272): UM->config() 
#6 /usr/local/lighthouse/softwares/wordpress/wp-includes/c in /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/um-polylang/includes/core/class-um-polylang.php on line 127
```

thank you

**Comment by umdevelopera** [comment]
Hi @sanitpeng 

This _Fatal error_ occurs if Polylang returns `bool` instead of the `PLL_Language` object. I can not reproduce this issue, Polylang returns a valid `PLL_Language` object on my site. Please describe steps needed to reproduce this issue.
I changed the code to avoid a _Fatal error_. Please try a version from the branch [development](https://github.com/umdevelopera/um-polylang/tree/development). 

Thanks
